### ISSUE TITLE
Absolute URLs in RSS feeds don't work

### ISSUE THREAD

**Issue by matrunchyk** [BlacksunLabs/blacksunlabs.github.io#15]
Hey guys! Thank you for your interesting blog!

Just wanted to let you know that RSS feed has relative-only URLs which makes it unusable in many RSS readers.
As a quick fix [this Jekyll plugin](https://github.com/eincs/jekyll-rss-absolute-urls) can be used, for example.

Thank you!

**Comment by xpcmdshell** [comment]
Hey, thanks for pointing out the relative-only URLs issue. I just updated our site generator config to include the base url, so it should spit out absolute URLs now. It looks to be working in my RSS reader now, let me know if you're still seeing any issues after refreshing in yours. 

Thanks,
actae0n
